### ISSUE TITLE
Allows `jobs` to be negative

### ISSUE THREAD

**Issue by Fuuzetsu** [asayers/patiently#1]
`-j-4` would then do something like `num_cpus::get().saturating_sub(4).max(1)`

I think `-j` usually doesn't support anything like this...

Of course this is just laziness on my side, feel free to close if you don't like it

Main use-case is to use nearly the whole machine but leave few cores so that it stays responsive

**Comment by asayers** [comment]
Nice idea.

**Comment by asayers** [comment]
Implemented.
